/*Desafio: loop faturamento por bairro*/
DECLARE @BAIRRO VARCHAR(50), @CIDADE VARCHAR(50) 
DECLARE @LINHAS_BAIRRO INT, @CONTADOR INT
DECLARE @TABELA_BAIRROS TABLE ([BAIRRO] VARCHAR(50))

SET @CIDADE = 'Rio de Janeiro'
SET @CONTADOR = 0

SELECT @LINHAS_BAIRRO = COUNT(*) FROM (
SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES]
WHERE CIDADE = @CIDADE) X

WHILE @CONTADOR < @LINHAS_BAIRRO
BEGIN
    SELECT DISTINCT @BAIRRO = BAIRRO FROM [TABELA DE CLIENTES]
    WHERE CIDADE = @CIDADE
    ORDER BY BAIRRO
    OFFSET @CONTADOR ROWS
    FETCH NEXT 1 ROWS ONLY
    INSERT INTO @TABELA_BAIRROS VALUES (@BAIRRO)
    SET @CONTADOR = @CONTADOR + 1
END
SELECT * FROM @TABELA_BAIRROS ORDER BY BAIRRO