/*Desafio: relatório de vendas*/
CREATE PROCEDURE faturamentoDepartamento (@dataInicial DATE, @dataFinal DATE)
AS
BEGIN
	DECLARE @DEPARTAMENTO TABLE (SABOR VARCHAR(20), DEPARTAMENTO VARCHAR(20))
	INSERT INTO @DEPARTAMENTO 
	SELECT DISTINCT SABOR, 'FRUTAS NÃO CÍTRICAS' as DEPARTAMENTO 
	FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('Açai','Cereja','Cereja/Maça','Maça','Manga','Maracujá','Melância')

	UNION

	SELECT DISTINCT SABOR, 'FRUTAS CÍTRICAS' as DEPARTAMENTO 
	FROM [TABELA DE PRODUTOS] WHERE SABOR IN ('Laranja','Uva','Limão','Morango','Morango/Limão','Lima/Limão')

	SELECT DP.[DEPARTAMENTO], SUM([ITENS NOTAS FISCAIS].QUANTIDADE * [ITENS NOTAS FISCAIS].[PREÇO]) AS FATURAMENTO
	FROM [TABELA DE PRODUTOS] INNER JOIN [ITENS NOTAS FISCAIS] ON [TABELA DE PRODUTOS].[CODIGO DO PRODUTO] = [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] INNER JOIN [NOTAS FISCAIS]  
	ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO INNER JOIN @DEPARTAMENTO DP ON [TABELA DE PRODUTOS].SABOR = DP.SABOR
	WHERE [NOTAS FISCAIS].DATA >= @dataInicial AND [NOTAS FISCAIS].DATA <= @dataFinal
	GROUP BY DP.[DEPARTAMENTO]
END


EXEC faturamentoDepartamento '2016-01-01','2016-01-15';